
- name: Configuration deployment
  hosts: FABRIC # <-- Targeted devices
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_server: 192.168.0.5
        cv_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjc2Mzk2MTU5MTE3NDUyOTA0OTUsImRzbiI6ImF2ZCIsImRzdCI6ImFjY291bnQiLCJleHAiOjE3NzkzNzE5OTksImlhdCI6MTc3ODgwMDY0MSwib2dpIjozLCJvZ24iOiJEZWZhdWx0Iiwic2lkIjoiNTg0Mjg1MTljYjFjZjJkNThmM2UxNzU4N2NmMDkzMTA1MGMxMTE3Nzg0YjNkZTU2NmFlYjZmZjQ0NzI2YTM0Mi00a3ZQZk1vZFlDWERiWmVlZU5zZ21LN1dlbHdnZ2VSdnNwdVVQZTZXIn0.PCbt7YS6Y2IR7QhswZnaBPBwmBS2kvcR-oTGidsEHMJjNh5ptKm9hVtHL0v3Rp8959B6DQcxJHaBsfaIQOTfna_0ucIYFJS-CpR1lC0hlnHjEg-VKZk1-TFgJgHbo8H1974DzKR-U9p9NtJevh-A9g2hILtdlazMwjLG3Z-fl6JPQa9u2Of2ax86TdMwul3v-eBKJ8YMLCU9g9GtA8BaXwHjE-lWik9Xkib9Q1R9DFPG22o_lyVyLugB94kHKKWK-OdTtDQBy79NIfUDTChv1HZMtLsJdbFYBeSJRw-YmUu4lpAV5acItNRxbjDz4KUbzSDUrA0nESYchVw72zH7u0Hyqq1UFl1vlaHiNPsHv994oinUpu7pMCZymM7fwobk7sujOHRNHbXRbmaKVhKiwWLA18nQIEk6nLb5bnVkcEI0tzvwAUoQW6_rU4vCpX9FMRiHhs6I-1gqaQN11DJFjvGggZGZY4j762NI-g6S6RIODiErDw9PaBsbJ8P1B7FBxxNRvrZCHde3-P6enT4tyz45OWWvCSl78QB1Fcln07i0_5D9jNZ0h1sM_FbZLIsg34SaUMTd54LMzyHSQLx9fGSY2i6PoqscDu_xvuTDtwfkvQsHEiC2C8da6QkVQLHqtJ8r6zdlY1p-HxAQJvvJ-KgKDjamOufCWAkoGd9FEmg
        cv_verify_certs: false
