
- name: Configuration deployment
  hosts: FABRIC # <-- Targeted devices
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_server: 192.168.0.5
        cv_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjc2Mzk2MTcyNzc1NDQ4OTA2MjQsImRzbiI6ImF2ZCIsImRzdCI6ImFjY291bnQiLCJleHAiOjE3NzkzNzE5OTksImlhdCI6MTc3ODgxNTg5MCwib2dpIjozLCJvZ24iOiJEZWZhdWx0Iiwic2lkIjoiOTNhYjVjMjFmZTA5MTc1YmEwNWMyZGNjNGNhMzBjMWFlMDczNjA4NjU1OTA2ODcwMTg1OTc0ZmZmYWM3YmIwYi0wdnV2TFJxTGNYTTdnRFdvN2paRDl0YVdqdDNIVEJvMXFFTVZHelZ1In0.Tk9Enn9sthyA0elllVghikMrqVKvRfgDEhOSdvQlIzJVQA1D_4EsiTHZtK2Zf5EMlJZoZS2glLYrivGP_CQxT484z0tbx4UBtF51l6SSB0nfbFwGjSGbyGTPw07WsJy3h8JBpM8tmfjVzv5hCPFFGngpr4xsmnkNBH7Yl9i0WjEDOgSJbYb__b3y1z72Wisp3GN-Rm29FIDb02zUHz9SIBoYpI2zV6FdCU4njIoROrrwumn1fvLzPfS39fFk60VU1a32Lw1EmYrLuJqIu82miiZBF-z33qBzUIglOVKOt09S3bAQ9EHYmf3DIbcD1VuWF0aRPIeOXH1X9ALKloUG81L1-qB_fSgDn_p29ggtVYaHWbjMJwPBYfP-Thc6H5KqicKJF8YfnFKbnTEzC-cpJMwR6sf9nMn_6INhDAXxGM8_J_7k6O63TzBlUVv0pPftKCbQbccuMAaxQ6DjkZIbfSF8qvKdcVrLzQg9x3lkPANjMh1Kfj9ks_H_TSqKp3gwJCd_wrOmdZZwxiuFEqgVTOOqBJK_1IEfcLdxm5lh_vqUPpe4xe2sGvnlNJ8u4td3rdhvTmvD5msrVWTG9u5xDrcCU-Ck-5G3GFX1jxPrwrM19ptzmyQXZ8Vep06XpYMBJuk_jvvyL8AcHDDbJwWBvILFe9ki0hvOafUT5k5esUE
        cv_verify_certs: false
